name: E2E on Chrome

on: [push]

env:
  NODE_ENV: 'stage'
  
jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Starting nodejs with ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: Install dependencies
        run: npm install

      - name: Print name
        run: echo "Hello $NODE_ENV"

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          browser: chrome
          record: true
          headless: true
          start: npm run stage
          wait-on: 'http://localhost:3000'
          wait-on: 'https://sanchoroz-facilicheck-server-stage.onrender.com/'
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
