name: Pull Request Workflow

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - master

env:
  ## Sets environment variables
  NODE_ENV: stage

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: step 1
        run: echo "The NODE_ENV key is:$NODE_ENV"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Starting nodejs with ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: Output secret
        run: echo "${{secrets.ACCESS_TOKEN}}"

      - name: Install dependencies
        run: npm install

      - name: Trigger Server Workflow
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          repository: sanchoroz/facilicheck-server
          event-type: setup-database

      - name: Run Prettier
        run: npm run format

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          browser: chrome
          headless: true
          record: true
          start: npm run stage
          wait-on: "http://localhost:3000/"
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
          REACT_APP_ENV: ${{secrets.REACT_APP_ENV}}

  merge-blocker:
    needs: install
    runs-on: ubuntu-latest
    if: ${{ needs.install.outcome != 'success' }}
      steps:
        - name: Block pull request merge
          run: exit 1