name: E2E on Chrome

on: [push]

env:
  ## Sets environment variable
  NODE_ENV: stage

jobs:
  install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: step 1
        run: echo "The NODE_ENV key is:$NODE_ENV"

      - name: Checkout
        uses: actions/checkout@v2

      - name: Starting nodejs with ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}

      - name: Install dependencies
        run: npm install

      - name: Cypress run
        uses: cypress-io/github-action@v3
        with:
          browser: chrome
          headless: true
          start: npm run stage
          wait-on: 'https://sanchoroz-facilicheck-server-stage.onrender.com'
          parallel: true
        env:
          CYPRESS_RECORD_KEY: ${{secrets.CYPRESS_RECORD_KEY}}
